"""
signals.py — the three independent detection signals.

  * llm_signal()         : semantic / holistic judgment via Groq      (Signal 1)
  * stylometric_signal() : structural / statistical heuristics (pure)  (Signal 2)
  * repetition_signal()  : internal redundancy / self-similarity (pure) (Signal 3, stretch S1)

Each returns P(AI) in [0, 1] plus explanatory detail. They are deliberately
independent: one reads meaning, one counts structure, one measures repetition.

llm_signal() is also multi-modal (stretch S4): pass content_type="image_caption"
to score an image description/alt-text with a caption-tuned prompt.
"""

import json
import math
import os
import re

from groq import Groq

LLM_MODEL = "llama-3.3-70b-versatile"

# Calibration guidance is part of the prompt: formality / non-native English is NOT
# treated as evidence of AI. This mitigates the model's documented bias against formal
# and ESL writing at the source — the single biggest false-positive risk in the system.
_LLM_SYSTEM_PROMPT = """You are a forensic text-analysis assistant for a creative-writing \
platform. Judge whether a passage was written by a human or generated by an AI language \
model, and estimate the probability that it is AI-generated.

Calibration rules you MUST follow:
- Formal, polished, or grammatically perfect writing is NOT by itself evidence of AI. Many \
humans write formally, especially non-native English speakers and academic or professional \
writers. Never raise your estimate for formality alone.
- Weigh genuine AI tells: generic "balanced" both-sides structure, stock transitions \
("furthermore", "it is important to note"), over-explaining, absence of specific lived \
detail, uniformly even rhythm, hedging with no real point of view.
- Weigh genuine human tells: concrete personal detail, idiosyncratic voice, irregular \
rhythm, clear opinion, slang, intentional fragments, surprising word choices.
- When the evidence is weak or mixed, return a probability near 0.5. Do not guess confidently.

Respond with ONLY a JSON object of exactly this shape:
{"ai_probability": <number 0..1>, "reasoning": "<one concise sentence>", \
"indicators": ["<short tell>", "<short tell>"]}"""

# Multi-modal (stretch S4): a caption-tuned variant for image descriptions / alt-text.
_CAPTION_SYSTEM_PROMPT = """You are a forensic analyst for a creative platform. Judge whether \
an IMAGE CAPTION / alt-text description was written by a human or generated by an AI vision \
model, and estimate the probability that it is AI-generated.

Calibration rules you MUST follow:
- Captions are short by nature; brevity is NOT evidence of either side.
- Weigh genuine AI-caption tells: formulaic openers ("an image of", "this image shows", \
"a photo of"), exhaustive literal completeness (naming every object/colour), generic \
adjectives ("beautiful", "serene"), and a flat, label-like tone with no point of view.
- Weigh genuine human tells: selective focus on what matters, personal/contextual reference \
("my dog Rufus", "taken last summer"), opinion or humour, informal phrasing, intentional \
incompleteness.
- When evidence is weak or mixed, return a probability near 0.5.

Respond with ONLY a JSON object of exactly this shape:
{"ai_probability": <number 0..1>, "reasoning": "<one concise sentence>", \
"indicators": ["<short tell>", "<short tell>"]}"""

_client: Groq | None = None


def _get_client() -> Groq:
    """Lazily construct the Groq client so importing this module never requires a key."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY", ""))
    return _client


def llm_signal(text: str, content_type: str = "text") -> dict:
    """
    Signal 1 — semantic. Ask Groq to assess human vs. AI authorship.

    content_type selects the prompt (stretch S4 multi-modal):
      "text"          -> general prose prompt
      "image_caption" -> caption/alt-text-tuned prompt

    Returns: {"ai_probability": float in [0,1], "reasoning": str,
              "indicators": [str, ...], "error": bool}

    Degrades gracefully: on any API/parse failure, returns a neutral 0.5 with
    error=True so the pipeline still produces an (honest, uncertain) result.
    """
    system_prompt = (
        _CAPTION_SYSTEM_PROMPT if content_type == "image_caption" else _LLM_SYSTEM_PROMPT
    )
    user_label = "Image caption to analyze" if content_type == "image_caption" else "Passage to analyze"
    try:
        resp = _get_client().chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"{user_label}:\n\n{text}"},
            ],
            temperature=0,
            max_tokens=400,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        prob = float(data.get("ai_probability"))
        prob = max(0.0, min(1.0, prob))  # clamp
        return {
            "ai_probability": round(prob, 3),
            "reasoning": str(data.get("reasoning", "")).strip(),
            "indicators": list(data.get("indicators", []))[:6],
            "error": False,
        }
    except Exception as exc:  # network error, bad JSON, missing key, etc.
        return {
            "ai_probability": 0.5,
            "reasoning": f"LLM signal unavailable ({type(exc).__name__}); defaulting to neutral.",
            "indicators": [],
            "error": True,
        }


# ----------------------------------------------------------------------------
# Signal 2 — stylometric heuristics (pure Python)
# ----------------------------------------------------------------------------

# Stock connective / templating phrases that AI prose reaches for repeatedly.
_AI_TELL_PHRASES = (
    "furthermore", "moreover", "in conclusion", "it is important to note",
    "it is worth noting", "it is essential", "important to consider", "delve",
    "navigate the complexities", "tapestry", "plays a crucial role",
    "plays a significant role", "plays a vital role", "in today's", "in the realm of",
    "a testament to", "underscores", "multifaceted", "paradigm shift", "ever-evolving",
    "ever-changing", "stakeholders", "transformative", "holistic", "leverage",
)

# Tight list of casual/slang tokens — kept small so semi-formal words don't
# falsely register as human informality.
_SLANG = {
    "honestly", "kinda", "gonna", "wanna", "yeah", "nah", "ok", "okay", "lol",
    "tbh", "ugh", "meh", "whatever", "dunno", "gotta", "lemme", "ya", "yep", "nope",
}

_CONTRACTION_RE = re.compile(r"\b[A-Za-z]+(?:n['’]t|['’](?:re|ve|ll|d|m))\b", re.IGNORECASE)
_CAPS_EMPHASIS_RE = re.compile(r"\b[A-Z]{3,}\b")  # len>=3 avoids acronyms like "AI"
_WORD_RE = re.compile(r"[A-Za-z']+")
_SENT_SPLIT_RE = re.compile(r"(?<=[.!?])\s+|\n+")


def _linmap(x: float, in_lo: float, in_hi: float, out_lo: float, out_hi: float) -> float:
    """Clamp x to [in_lo,in_hi] then linearly map onto [out_lo,out_hi] (either direction)."""
    if in_hi == in_lo:
        return (out_lo + out_hi) / 2
    t = max(0.0, min(1.0, (x - in_lo) / (in_hi - in_lo)))
    return out_lo + t * (out_hi - out_lo)


def stylometric_signal(text: str) -> tuple[float, dict]:
    """
    Signal 2 — structural. Four sub-metrics, each mapped to an AI-ness contribution
    in [0,1], then weighted into a single stylo_score = P(AI).

      burstiness    : low sentence-length variation  -> AI-like   (weight 0.40)
      ai_phrases    : density of stock AI phrases     -> AI-like   (weight 0.30)
      informality   : casual human markers (presence) -> human     (weight 0.20)
      ttr           : lexical diversity (weak signal)              (weight 0.10)

    Design choices that protect against false positives:
      * Absence of informality and absence of AI phrases map to a NEUTRAL 0.5, not to
        "AI" — so formal human writing is never pushed toward AI on those axes alone.
      * Very short text makes variance/TTR meaningless, so the score is damped toward
        0.5 and flagged `reliable=False`.

    Returns (stylo_score, detail_dict).
    """
    sentences = [s.strip() for s in _SENT_SPLIT_RE.split(text) if s.strip()]
    words = _WORD_RE.findall(text.lower())
    n_sent = len(sentences)
    n_words = len(words)

    # ---- sub-metric 1: sentence-length burstiness (coefficient of variation) ----
    sent_lens = [len(_WORD_RE.findall(s)) for s in sentences]
    sent_lens = [n for n in sent_lens if n > 0]
    if len(sent_lens) >= 2:
        mean_len = sum(sent_lens) / len(sent_lens)
        variance = sum((n - mean_len) ** 2 for n in sent_lens) / len(sent_lens)
        cv = (math.sqrt(variance) / mean_len) if mean_len else 0.0
    else:
        mean_len = float(sent_lens[0]) if sent_lens else 0.0
        cv = 0.0
    ai_burst = _linmap(cv, 0.25, 0.65, 0.85, 0.15)  # low CV -> AI, high CV -> human

    # ---- sub-metric 2: type-token ratio (capped at first 100 tokens for length-stability) ----
    window = words[:100]
    ttr = (len(set(window)) / len(window)) if window else 0.5
    ai_ttr = _linmap(ttr, 0.40, 0.70, 0.65, 0.35)  # very low diversity nudges mildly AI

    # ---- sub-metric 3: informality / human-casual markers (presence pulls toward human) ----
    lowercase_starts = sum(
        1 for s in sentences if s[:1].isalpha() and s[:1].islower()
    )
    contractions = len(_CONTRACTION_RE.findall(text))
    caps_emphasis = len(_CAPS_EMPHASIS_RE.findall(text))
    slang_hits = sum(1 for w in words if w in _SLANG)
    ellipses = text.count("...") + text.count("…")
    multi_punct = len(re.findall(r"[!?]{2,}", text))
    informality_markers = (
        lowercase_starts + contractions + caps_emphasis + slang_hits + ellipses + multi_punct
    )
    informality_density = informality_markers / n_sent if n_sent else 0.0
    ai_informal = _linmap(informality_density, 0.0, 1.0, 0.5, 0.1)  # absence neutral, presence human

    # ---- sub-metric 4: AI-tell phrase density (presence pushes toward AI) ----
    low = text.lower()
    ai_phrase_hits = sum(low.count(p) for p in _AI_TELL_PHRASES)
    ai_phrase_density = ai_phrase_hits / n_sent if n_sent else 0.0
    ai_phrases = _linmap(ai_phrase_density, 0.0, 0.6, 0.5, 0.95)  # absence neutral, presence AI

    stylo_score = (
        0.40 * ai_burst + 0.30 * ai_phrases + 0.20 * ai_informal + 0.10 * ai_ttr
    )

    # ---- short-text guard: damp toward 0.5 when statistics are unreliable ----
    reliable = n_sent >= 3 and n_words >= 25
    if not reliable:
        stylo_score = 0.5 + (stylo_score - 0.5) * 0.4

    stylo_score = round(max(0.0, min(1.0, stylo_score)), 3)

    detail = {
        "sentence_count": n_sent,
        "word_count": n_words,
        "mean_sentence_length": round(mean_len, 2),
        "sentence_length_cv": round(cv, 3),
        "type_token_ratio": round(ttr, 3),
        "informality_markers": informality_markers,
        "informality_density": round(informality_density, 3),
        "ai_phrase_hits": ai_phrase_hits,
        "reliable": reliable,
        "sub_scores": {
            "burstiness": round(ai_burst, 3),
            "ai_phrases": round(ai_phrases, 3),
            "informality": round(ai_informal, 3),
            "ttr": round(ai_ttr, 3),
        },
    }
    return stylo_score, detail


# ----------------------------------------------------------------------------
# Signal 3 — repetition / redundancy (pure Python)  [stretch S1: ensemble]
# ----------------------------------------------------------------------------

# Below this word count, redundancy is statistically meaningless AND low repetition is
# not evidence of human authorship — so the signal abstains instead of voting.
REPETITION_MIN_WORDS = 60


def repetition_signal(text: str) -> tuple[float, dict]:
    """
    Signal 3 — internal self-similarity. Measures how much the text repeats itself
    (repeated trigrams, repeated bigrams, repeated sentence openings). Un-edited AI prose
    loops and reuses phrasings; humans repeat less mechanically. High redundancy -> AI.

    Distinct from Signal 2: burstiness is about sentence *length* and TTR about *vocabulary*;
    this is about *repetition of content/structure*.

    Returns (score, detail). When the text is shorter than REPETITION_MIN_WORDS, the signal
    ABSTAINS: detail["participates"] is False and the caller leaves it out of the ensemble.
    """
    words = _WORD_RE.findall(text.lower())
    n_words = len(words)

    if n_words < REPETITION_MIN_WORDS:
        return 0.5, {
            "participates": False,
            "word_count": n_words,
            "reason": f"abstains: <{REPETITION_MIN_WORDS} words, redundancy not reliably measurable",
        }

    trigrams = list(zip(words, words[1:], words[2:]))
    bigrams = list(zip(words, words[1:]))
    trigram_redundancy = 1 - len(set(trigrams)) / len(trigrams) if trigrams else 0.0
    bigram_redundancy = 1 - len(set(bigrams)) / len(bigrams) if bigrams else 0.0

    sentences = [s.strip() for s in _SENT_SPLIT_RE.split(text) if s.strip()]
    openers = [tuple(_WORD_RE.findall(s.lower())[:2]) for s in sentences if _WORD_RE.findall(s)]
    repeated_openers = (len(openers) - len(set(openers))) / len(openers) if openers else 0.0

    redundancy = 0.5 * trigram_redundancy + 0.3 * bigram_redundancy + 0.2 * repeated_openers
    # absence of repetition is ~neutral; high repetition pushes toward AI.
    rep_score = round(max(0.0, min(1.0, _linmap(redundancy, 0.03, 0.18, 0.47, 0.92))), 3)

    detail = {
        "participates": True,
        "word_count": n_words,
        "trigram_redundancy": round(trigram_redundancy, 3),
        "bigram_redundancy": round(bigram_redundancy, 3),
        "repeated_openers": round(repeated_openers, 3),
        "redundancy": round(redundancy, 3),
    }
    return rep_score, detail

